version: 2
jobs:
  build:
    working_directory: /root/project
    docker:
        - image: truffle/ci:latest
    steps:
      - checkout

      - run: npm install -g npm
      - run: npm install
      - run: npm i truffle
      - run: npm install -g  ganache-cli
      - run: ganache-cli -h 127.0.0.1 -p 7545 & ./node_modules/.bin/truffle test
